# Generated by Django 5.0.3 on 2024-04-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_coinflip_delete_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinFlip',
        ),
    ]
